//also change this variable to randomization_partID
//array of objects that contains randomization
//for the trials and the puzzle piece randomization for one participant
//each object is a new trial
var randomization = [
  {
    "trial": "trial_runPuppy",
    "position 1": 1,
    "position 2": 12,
    "position 3": 2,
    "position 4": 11,
    "position 5": 3,
    "position 6": 10,
    "position 7": 4,
    "position 8": 9,
    "position 9": 5,
    "position 10": 8,
    "position 11": 6,
    "position 12": 7
  },
  {
    "trial": "trial_otter",
    "position 1": 1,
    "position 2": 3,
    "position 3": 5,
    "position 4": 7,
    "position 5": 9,
    "position 6": 11,
    "position 7": 2,
    "position 8": 4,
    "position 9": 6,
    "position 10": 8,
    "position 11": 10,
    "position 12": 12
  },
  {
    "trial": "trial_alpaca",
    "position 1": 1,
    "position 2": 4,
    "position 3": 7,
    "position 4": 10,
    "position 5": 2,
    "position 6": 5,
    "position 7": 8,
    "position 8": 11,
    "position 9": 3,
    "position 10": 6,
    "position 11": 9,
    "position 12": 12
  },
  {
    "trial": "trial_otters",
    "position 1": 1,
    "position 2": 3,
    "position 3": 5,
    "position 4": 7,
    "position 5": 9,
    "position 6": 11,
    "position 7": 2,
    "position 8": 4,
    "position 9": 6,
    "position 10": 8,
    "position 11": 10,
    "position 12": 12
  },
  {
    "trial": "trial_toronto",
    "position 1": 12,
    "position 2": 10,
    "position 3": 8,
    "position 4": 6,
    "position 5": 4,
    "position 6": 2,
    "position 7": 11,
    "position 8": 9,
    "position 9": 7,
    "position 10": 5,
    "position 11": 3,
    "position 12": 1
  },
  {
    "trial": "trial_monkey",
    "position 1": 5,
    "position 2": 6,
    "position 3": 10,
    "position 4": 4,
    "position 5": 7,
    "position 6": 1,
    "position 7": 9,
    "position 8": 2,
    "position 9": 3,
    "position 10": 8,
    "position 11": 11,
    "position 12": 12
  },
  {
    "trial": "trial_acadia",
    "position 1": 12,
    "position 2": 3,
    "position 3": 5,
    "position 4": 7,
    "position 5": 9,
    "position 6": 11,
    "position 7": 2,
    "position 8": 4,
    "position 9": 6,
    "position 10": 8,
    "position 11": 10,
    "position 12": 1
    },
    {
    "trial": "trial_SU",
    "position 1": 7,
    "position 2": 3,
    "position 3": 5,
    "position 4": 1,
    "position 5": 9,
    "position 6": 8,
    "position 7": 2,
    "position 8": 4,
    "position 9": 6,
    "position 10": 11,
    "position 11": 10,
    "position 12": 12
    }
    ]
