var randomization = [                                                                               //also change this variable to randomization_partID
    {
      "trial": "trial_8",
      "image piece on poisition (1,1)": 1,                                                          //array of objects that contains randomization
      "image piece on poisition (1,2)": 2,                                                          //for the trials and the puzzle piece randomization for one participant
      "image piece on poisition (1,3)": 3,                                                          //each object is a new trial
      "image piece on poisition (1,4)": 4,
      "image piece on poisition (1,5)": 5,
      "image piece on poisition (1,6)": 6,
      "image piece on poisition (2,1)": 7,
      "image piece on poisition (2,2)": 8,
      "image piece on poisition (2,3)": 9,
      "image piece on poisition (2,4)": 10,
      "image piece on poisition (2,5)": 11,
      "image piece on poisition (2,6)": 12
    },
    {
      "trial": "trial_2",
      "image piece on poisition (1,1)": 1,
      "image piece on poisition (1,2)": 2,
      "image piece on poisition (1,3)": 3,
      "image piece on poisition (1,4)": 4,
      "image piece on poisition (1,5)": 5,
      "image piece on poisition (1,6)": 6,
      "image piece on poisition (2,1)": 7,
      "image piece on poisition (2,2)": 8,
      "image piece on poisition (2,3)": 9,
      "image piece on poisition (2,4)": 10,
      "image piece on poisition (2,5)": 11,
      "image piece on poisition (2,6)": 12
    },
    {
      "trial": "trial_3",
      "image piece on poisition (1,1)": 1,
      "image piece on poisition (1,2)": 2,
      "image piece on poisition (1,3)": 3,
      "image piece on poisition (1,4)": 4,
      "image piece on poisition (1,5)": 5,
      "image piece on poisition (1,6)": 6,
      "image piece on poisition (2,1)": 7,
      "image piece on poisition (2,2)": 8,
      "image piece on poisition (2,3)": 9,
      "image piece on poisition (2,4)": 10,
      "image piece on poisition (2,5)": 11,
      "image piece on poisition (2,6)": 12
    },
    {
      "trial": "trial_4",
      "image piece on poisition (1,1)": 1,
      "image piece on poisition (1,2)": 2,
      "image piece on poisition (1,3)": 3,
      "image piece on poisition (1,4)": 4,
      "image piece on poisition (1,5)": 5,
      "image piece on poisition (1,6)": 6,
      "image piece on poisition (2,1)": 7,
      "image piece on poisition (2,2)": 8,
      "image piece on poisition (2,3)": 9,
      "image piece on poisition (2,4)": 10,
      "image piece on poisition (2,5)": 11,
      "image piece on poisition (2,6)": 12
    },
    {
      "trial": "trial_5",
      "image piece on poisition (1,1)": 1,
      "image piece on poisition (1,2)": 2,
      "image piece on poisition (1,3)": 3,
      "image piece on poisition (1,4)": 4,
      "image piece on poisition (1,5)": 5,
      "image piece on poisition (1,6)": 6,
      "image piece on poisition (2,1)": 7,
      "image piece on poisition (2,2)": 8,
      "image piece on poisition (2,3)": 9,
      "image piece on poisition (2,4)": 10,
      "image piece on poisition (2,5)": 11,
      "image piece on poisition (2,6)": 12
    },
    {
      "trial": "trial_6",
      "image piece on poisition (1,1)": 1,
      "image piece on poisition (1,2)": 2,
      "image piece on poisition (1,3)": 3,
      "image piece on poisition (1,4)": 4,
      "image piece on poisition (1,5)": 5,
      "image piece on poisition (1,6)": 6,
      "image piece on poisition (2,1)": 7,
      "image piece on poisition (2,2)": 8,
      "image piece on poisition (2,3)": 9,
      "image piece on poisition (2,4)": 10,
      "image piece on poisition (2,5)": 11,
      "image piece on poisition (2,6)": 12
    },
    {
      "trial": "trial_7",
      "image piece on poisition (1,1)": 1,
      "image piece on poisition (1,2)": 2,
      "image piece on poisition (1,3)": 3,
      "image piece on poisition (1,4)": 4,
      "image piece on poisition (1,5)": 5,
      "image piece on poisition (1,6)": 6,
      "image piece on poisition (2,1)": 7,
      "image piece on poisition (2,2)": 8,
      "image piece on poisition (2,3)": 9,
      "image piece on poisition (2,4)": 10,
      "image piece on poisition (2,5)": 11,
      "image piece on poisition (2,6)": 12
    },
    {
      "trial": "trial_1",
      "image piece on poisition (1,1)": 1,
      "image piece on poisition (1,2)": 2,
      "image piece on poisition (1,3)": 3,
      "image piece on poisition (1,4)": 4,
      "image piece on poisition (1,5)": 5,
      "image piece on poisition (1,6)": 6,
      "image piece on poisition (2,1)": 7,
      "image piece on poisition (2,2)": 8,
      "image piece on poisition (2,3)": 9,
      "image piece on poisition (2,4)": 10,
      "image piece on poisition (2,5)": 11,
      "image piece on poisition (2,6)": 12
    }
   ]