var randomization = [                                                                               //also change this variable to randomization_partID
    {
      "trial": "trial_runPuppy",
      "image piece on poisition (1)": 1,                                                             //array of objects that contains randomization
      "image piece on poisition (2)": 12,                                                            //for the trials and the puzzle piece randomization for one participant
      "image piece on poisition (3)": 2,                                                           //each object is a new trial
      "image piece on poisition (4)": 11,
      "image piece on poisition (5)": 3,
      "image piece on poisition (6)": 10,
      "image piece on poisition (7)": 4,
      "image piece on poisition (8)": 9,
      "image piece on poisition (9)": 5,
      "image piece on poisition (10)": 8,
      "image piece on poisition (11)": 6,
      "image piece on poisition (12)": 7
    },
    {
      "trial": "trial_otter",
      "image piece on poisition (1)": 1,
      "image piece on poisition (2)": 3,
      "image piece on poisition (3)": 5,
      "image piece on poisition (4)": 7,
      "image piece on poisition (5)": 9,
      "image piece on poisition (6)": 11,
      "image piece on poisition (7)": 2,
      "image piece on poisition (8)": 4,
      "image piece on poisition (9)": 6,
      "image piece on poisition (10)": 8,
      "image piece on poisition (11)": 10,
      "image piece on poisition (12)": 12
    },
    {
      "trial": "trial_alpaca",
      "image piece on poisition (1)": 1,
      "image piece on poisition (2)": 4,
      "image piece on poisition (3)": 7,
      "image piece on poisition (4)": 10,
      "image piece on poisition (5)": 2,
      "image piece on poisition (6)": 5,
      "image piece on poisition (7)": 8,
      "image piece on poisition (8)": 11,
      "image piece on poisition (9)": 3,
      "image piece on poisition (10)": 6,
      "image piece on poisition (11)": 9,
      "image piece on poisition (12)": 12
    },
    {
      "trial": "trial_otters",
      "image piece on poisition (1)": 1,
      "image piece on poisition (2)": 3,
      "image piece on poisition (3)": 5,
      "image piece on poisition (4)": 7,
      "image piece on poisition (5)": 9,
      "image piece on poisition (6)": 11,
      "image piece on poisition (7)": 2,
      "image piece on poisition (8)": 4,
      "image piece on poisition (9)": 6,
      "image piece on poisition (10)": 8,
      "image piece on poisition (11)": 10,
      "image piece on poisition (12)": 12
    },
    {
      "trial": "trial_toronto",
      "image piece on poisition (1)": 12,
      "image piece on poisition (2)": 10,
      "image piece on poisition (3)": 8,
      "image piece on poisition (4)": 6,
      "image piece on poisition (5)": 4,
      "image piece on poisition (6)": 2,
      "image piece on poisition (7)": 11,
      "image piece on poisition (8)": 9,
      "image piece on poisition (9)": 7,
      "image piece on poisition (10)": 5,
      "image piece on poisition (11)": 3,
      "image piece on poisition (12)": 1
    },
    {
      "trial": "trial_monkey",
      "image piece on poisition (1)": 5,
      "image piece on poisition (2)": 6,
      "image piece on poisition (3)": 10,
      "image piece on poisition (4)": 4,
      "image piece on poisition (5)": 7,
      "image piece on poisition (6)": 1,
      "image piece on poisition (7)": 9,
      "image piece on poisition (8)": 2,
      "image piece on poisition (9)": 3,
      "image piece on poisition (10)": 8,
      "image piece on poisition (11)": 11,
      "image piece on poisition (12)": 12
    },
    {
      "trial": "trial_acadia",
      "image piece on poisition (1)": 12,
      "image piece on poisition (2)": 3,
      "image piece on poisition (3)": 5,
      "image piece on poisition (4)": 7,
      "image piece on poisition (5)": 9,
      "image piece on poisition (6)": 11,
      "image piece on poisition (7)": 2,
      "image piece on poisition (8)": 4,
      "image piece on poisition (9)": 6,
      "image piece on poisition (10)": 8,
      "image piece on poisition (11)": 10,
      "image piece on poisition (12)": 1
    },
    {
      "trial": "trial_SU",
      "image piece on poisition (1)": 7,
      "image piece on poisition (2)": 3,
      "image piece on poisition (3)": 5,
      "image piece on poisition (4)": 1,
      "image piece on poisition (5)": 9,
      "image piece on poisition (6)": 8,
      "image piece on poisition (7)": 2,
      "image piece on poisition (8)": 4,
      "image piece on poisition (9)": 6,
      "image piece on poisition (10)": 11,
      "image piece on poisition (11)": 10,
      "image piece on poisition (12)": 12
    }
   ]